// Plan de départ SYSCOHADA révisé (OHADA) — comptes courants d'une
// entreprise de distribution. À compléter / valider par l'expert-comptable.
export const SYSCOHADA_DEPART = [
  { numero_compte: '101000', libelle: 'Capital social' },
  { numero_compte: '311000', libelle: 'Marchandises' },
  { numero_compte: '401100', libelle: 'Fournisseurs' },
  { numero_compte: '411100', libelle: 'Clients' },
  { numero_compte: '421000', libelle: 'Personnel, avances et acomptes' },
  { numero_compte: '422000', libelle: 'Personnel, rémunérations dues' },
  { numero_compte: '443100', libelle: 'État, TVA facturée sur ventes' },
  { numero_compte: '445200', libelle: 'État, TVA récupérable sur achats' },
  { numero_compte: '471000', libelle: 'Débiteurs et créditeurs divers' },
  { numero_compte: '521000', libelle: 'Banques locales' },
  { numero_compte: '571100', libelle: 'Caisse en monnaie nationale' },
  { numero_compte: '585000', libelle: 'Virements de fonds' },
  { numero_compte: '601100', libelle: 'Achats de marchandises' },
  { numero_compte: '603100', libelle: 'Variations des stocks de marchandises' },
  { numero_compte: '605100', libelle: 'Fournitures non stockables — eau' },
  { numero_compte: '605200', libelle: 'Fournitures non stockables — électricité' },
  { numero_compte: '605500', libelle: 'Fournitures de bureau' },
  { numero_compte: '611000', libelle: 'Transports sur achats' },
  { numero_compte: '612000', libelle: 'Transports sur ventes' },
  { numero_compte: '622000', libelle: 'Locations et charges locatives' },
  { numero_compte: '624000', libelle: 'Entretien, réparations et maintenance' },
  { numero_compte: '625000', libelle: "Primes d'assurance" },
  { numero_compte: '627000', libelle: 'Publicité, publications, relations publiques' },
  { numero_compte: '628000', libelle: 'Frais de télécommunications' },
  { numero_compte: '631000', libelle: 'Frais bancaires' },
  { numero_compte: '632400', libelle: 'Honoraires' },
  { numero_compte: '658000', libelle: 'Charges diverses' },
  { numero_compte: '661000', libelle: 'Rémunérations directes versées au personnel national' },
  { numero_compte: '701100', libelle: 'Ventes de marchandises' },
  { numero_compte: '707000', libelle: 'Produits accessoires' },
  { numero_compte: '758000', libelle: 'Produits divers' },
]
